version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: qikserve-container
    environment:
      POSTGRES_DB: "qikserve-test-db"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
